### ISSUE TITLE
update william rowland's contact information

### ISSUE THREAD

**Issue by amilan17** [hpde/SMWG#1]
He works at NOAA. 
<Spase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns="http://www.spase-group.org/data/schema" xsi:schemaLocation="http://www.spase-group.org/data/schema http://www.spase-group.org/data/schema/spase-2_2_6.xsd">
    <Version>2.2.6</Version>
    <Person>
        <ResourceID>spase://SMWG/Person/William.F.Rowland</ResourceID>
        <PersonName>William Rowland</PersonName>
        <OrganizationName>NOAA National Centers for Environmental Information</OrganizationName>
        <Email>William.Rowland@noaa.gov</Email>
        <PhoneNumber>303-497-3708</PhoneNumber>
    </Person>
</Spase>

**Comment by jweygand** [comment]
Anna, 
Sorry, are you asking me to update this information and the version? 
thanks, 
j

**Comment by amilan17** [comment]
Hi - My apologies - I already updated it, but I'm not sure if there is a
process beyond this.

Anna
_~~~~~~Metadata Adds Meaning~~~~~~_
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
(formerly NOAA’s National Geophysical Data Center)
http://www.ngdc.noaa.gov/metadata/emma
_~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_

**Comment by jweygand** [comment]
Ok, super. Thanks, j 
P.S. If you pushed the modification, then there is 
nothing more to do.

**Comment by tressahelvey** [comment]
Issue was resolved in 2016
