### ISSUE TITLE
Fixing CI ?

### ISSUE THREAD

**Issue by BaptisteCecconi** [hpde/SMWG#10]
Is there a plan to fix the CI script ? 
See commit: 280b1a8

**Comment by toddking** [comment]
Hi Baptiste -

In principal, yes. GitHub made changes to the way action scripts work to address a security issue. Unfortunately, the changes broke the existing script. The documentation for action scripts isn't very good (at least it was too vague for me). I plan to dig into it deeper and restore the validation, hopefully in the near future.

-Todd-

________________________________

**Comment by rchimiak** [comment]
Todd,

This issue is now resolved.  Could you please close it if appropriate.

**Comment by toddking** [comment]
CI works again. Resolved by re-writing GitHub actions.

**Comment by toddking** [comment]
Issue closed.

________________________________
