### ISSUE TITLE
About French ground facilities naming.

### ISSUE THREAD

**Issue by BaptisteCecconi** [hpde/SMWG#3]
I'm trying to prepare a future series of resource inputs into the SPASE registry, and I just reviewed the French ground facility resources linked to Observatoire de Paris:

## Observatory Tree
I spotted those 3 entries:
- `spase://SMWG/Observatory/OBSPM`
- `spase://SMWG/Observatory/Meudon`
- `spase://SMWG/Observatory/NANCAY`

 I think that each of the resources need to be updated, their name should be changed and the hierarchy strongly modified. From the content of the resource descriptors, it looks like `spase://SMWG/Observatory/OBSPM` refers to solar observation facilities at Meudon. This is misleading as: `obspm` is part of the DNS of the Observatoire de Paris (with labs and instruments in Paris and Meudon, and concerning many science disciplines). The `spase://SMWG/Observatory/Meudon` resource looks a bit orphaned here. The `spase://SMWG/Observatory/NANCAY` is hosting several instruments of interest for the SPASE registry. So in any cases, we should probably reorganize the resource tree for those entries as follows:
- `spase://SMWG/Observatory/ObsParis`
- `spase://SMWG/Observatory/ObsNancay`

Note that the official name the *ObsParis* is *Observatoire de Paris*, although its DNS is `obspm.fr`. *ObsParis* is a single entity including the Paris and Meudon physical sites.

## Instrument Tree
I spotted those 3 entries:
- `spase://SMWG/Instrument/Meudon/Spectroheliograph`
- `spase://SMWG/Instrument/OBSPM/OBSPM`
- `spase://SMWG/Instrument/NANCAY/Radioheliograph`

These instruments should be listed in the SPASE registry. In the local LESIA documentation, there is no difference between the `spase://SMWG/Instrument/Meudon/Spectroheliograph` and `spase://SMWG/Instrument/OBSPM/OBSPM` instrument and they are referred to as * Spectroheliograph*. So that I propose to reorganize the tree this way:
- `spase://SMWG/Instrument/ObsParis/Spectroheliograph`
- `spase://SMWG/Instrument/ObsNancay/Radioheliograph`

We may want to keep the `Meudon` name in the SPASE hierarchy, so we could have `spase://SMWG/Instrument/ObsParis/Meudon/Spectroheliograph` instead. 

I need to add 3 new entries in the `ObsNancay` tree:
- `spase://SMWG/Instrument/ObsNancay/NDA` for the *Nancay Decameter Array*
- `spase://SMWG/Instrument/ObsNancay/FR606` for the *FR606 LOFAR international station*
- `spase://SMWG/Instrument/ObsNancay/NenuFAR` for the *NenuFAR* instrument

**NB: I will update the issue later, as the [spase-group.org](http://www.spase-group.org) website looks down for now**

**Comment by BaptisteCecconi** [comment]
Here is the new proposed scheme for `SWMG/Observatory`:
* `spase://SMWG/Observatory/ObsNancay` for the description of the Nancay Radio Astronomy facility. 
* `spase://SMWG/Observatory/ObsNancay/FR606` for the description of the LOFAR-FR606 facility (part of the International LOFAR Telescope). 
* `spase://SMWG/Observatory/ObsNancay/NDA` for the Nancay Decameter Array
* `spase://SMWG/Observatory/ObsNancay/NRH` for the Nancay Radio Heliograph
* `spase://SMWG/Observatory/ObsNancay/NRT` for the Nancay Radio Telescope
* `spase://SMWG/Observatory/ObsNancay/NenuFAR` for the NenuFAR array
* `spase://SMWG/Observatory/ObsParis` for the description of the Paris Observatory

Here is the new proposed scheme for `SWMG/Instrument`:
* `spase://SMWG/Instrument/ObsParis/Meudon/Heliograph` for the Heliograph instrument in Meudon (previously `spase://SMWG/Instrument/OBSPM/OSBPM`)
* `spase://SMWG/Instrument/ObsParis/Meudon/Spectroheliograph` for the Spectro Heliograph in Meudon (previously `spase://SMWG/Instrument/Meudon/Spectroheliograph`)
* `spase://SMWG/Instrument/ObsParis/Meudon/SID` for the SID receiver in Meudon.
* `spase://SMWG/Instrument/ObsNancay/FR606/HBA` for the High frequency Band Array instrument of LOLFAR-FR606
* `spase://SMWG/Instrument/ObsNancay/FR606/LBA` for the Low frequency Band Array instrument of LOLFAR-FR606
* `spase://SMWG/Instrument/ObsNancay/NDA/JunoN` for the Juno-Nancay radio receiver connected on NDA 
* `spase://SMWG/Instrument/ObsNancay/NDA/NewRoutine` for the NewRoutine radio receiver connected on NDA 
* `spase://SMWG/Instrument/ObsNancay/NDA/Routine` for the Routine radio receiver connected on NDA 
* `spase://SMWG/Instrument/ObsNancay/NRH` for the NRH instrument (previously `spase://SMWG/Instrument/NANCAY/Radioheliograph.xml`) 
* `spase://SMWG/Instrument/ObsNancay/NenuFAR` for the NenuFAR instrument 

Here is the new proposed scheme for `SWMG/Repository`:
* `spase://SMWG/Repository/PADC` for the *Paris Astronomical Data Centre*
* `spase://SMWG/Repository/PADC/APIS` for the *Auroral Planetary Imaging and Spectra* database
* `spase://SMWG/Repository/PADC/BASS2000` for the *Base de Données Solaire* database
* `spase://SMWG/Repository/PADC/HELIO_HFC` for the *HELIO Feature Catalogue* database
* `spase://SMWG/Repository/PADC/MASER` for the *MASER* Repository

I will submit those changes internally for review and comments and then issue the pull request.

**Comment by J-Christophe** [comment]
Hello Baptiste,

I suggest that we use existing identifiers for observatories provided by IAU : https://en.wikipedia.org/wiki/List_of_observatory_codes. This is an interoperability issue. If you we use something already standardized, softwares could easily attach some information (e: longitude, latitude, latitude of the observatory) coming from somewhere to our data without creating a mapping file (which is not interoperable)

In addition, this observatory code seems to be used in other softwares : http://dc.zah.uni-heidelberg.de/obscode/q/query/form

If one code is missing, we could provide an input to IAU. If it takes too much time, we could add a kind of name space to define the authority (IAU, you, me, SPACE). 

So for Meudon, we could have spase://SMWG/Observatory/IAU:OBS:005. For Nançay, which is not is the list, we will get space://SMWG/Observatory/SPACE:OBS:Nancay

Jean-Christophe

**Comment by BaptisteCecconi** [comment]
Hi Jean-Christophe,

two remarks:
- the SPASE data model and registry has been used for years (decades?) so it is not a new thing :-)
- the interoperability is indeed important. In the case of SPASE, a very small number of observatories will also be described in the IAU list. I would rather suggest to have an AlternateID element in the data model, so that we can link with this other ID. However this would be a limited interoperability as the IAU team doesn’t provide us with a URN scheme for their IDs.

By the way, the alternateID could also be used in other resource descriptors, such as the Person tree, with ORCIDs.

Baptiste
